### PR TITLE
hio id 使用64位

### PR DESCRIPTION
**Pull request by fuzhufang**

### CODE REVIEW

**Comment by ithewei** [comment]
Why need 64 bits？

**Comment by fuzhufang** [comment]
As a service process, it may be opened for 1 year or even longer. If the connection creation of this service is disconnected frequently, then the self-incrementing id may exceed 2^32-1. However, if 64 bits are used, even if it is incremented by 1 in 1 millisecond, it will take hundreds of millions of years for an overflow to occur. In theory, it can be considered that an exception will not occur. However, I am a little worried. 32 bits are indeed enough for now.

**Comment by fuzhufang** [comment]
Do you think it needs to be modified? If not, I will close it.

**Comment by ithewei** [comment]
> Do you think it needs to be modified? If not, I will close it.

Yes,  I think 32 bits are enough for now.

**Pull request closed without merging**
